#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
INSTALL_DIR=$(realpath ${SCRIPT_DIR}/../sysroot)
#Release Debug 
cmake  -DCMAKE_BUILD_TYPE:STRING="Release" -DFUNDAMENTAL_BUILD_NETWORK=OFF -DIMPORT_GTEST=OFF -DIMPORT_BENCHMARK=OFF \
-DFUNDAMENTAL_BUILD_EVENTS=OFF -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DTest_INSTALL=ON -DFUNDAMENTAL_BUILD_RTTR=OFF  -S . -B ./build-linux-r 

