if(__source_import_config__)
    return()
endif()
set(__source_import_config__ TRUE)
if(NOT FUNDAMENTAL_IMPORT_SRC)
    return()
endif()

if(FUNDAMENTAL_MAIN_PROJECT)
    option(FUNDAMENTAL_ENABLE_DATABASE_SUPPORT "enable database support." ON)
    option(FUNDAMENTAL_ENABLE_SCRIPT_SUPPORT "enable chaiscript support." ON)
    option(FUNDAMENTAL_BUILD_NETWORK "enable build of fundamental network library." ON)
else()
    option(FUNDAMENTAL_ENABLE_DATABASE_SUPPORT "enable database support." OFF)
    option(FUNDAMENTAL_ENABLE_SCRIPT_SUPPORT "enable chaiscript support." OFF)
    option(FUNDAMENTAL_BUILD_NETWORK "enable build of fundamental network library." OFF)
endif()


if(FUNDAMENTAL_MAIN_PROJECT)
    option(FUNDAMENTAL_BUILD_RTTR "enable build of fundamental rttr module." ON)
    option(FUNDAMENTAL_BUILD_EVENTS "enable build of fundamental events module." ON)
    option(IMPORT_BENCHMARK "import benchmark" ON)
    option(IMPORT_GTEST "import gtest" ON)
else()
    option(FUNDAMENTAL_BUILD_RTTR "enable build of fundamental rttr module." ${FUNDAMENTAL_BUILD_NETWORK})
    option(FUNDAMENTAL_BUILD_EVENTS "enable build of fundamental events module." ${FUNDAMENTAL_BUILD_NETWORK})
    option(IMPORT_BENCHMARK "import benchmark" OFF)
    option(IMPORT_GTEST "import gtest" OFF)
endif()
option(DISABLE_DEBUG_SANITIZE_ADDRESS_CHECK "disable debug mode sanitize address check" OFF)

option(FUNDAMENTAL_ENABLE_SQLITE3_SUPPORT "enable sqlite3 database support." ${FUNDAMENTAL_ENABLE_DATABASE_SUPPORT})
option(FUNDAMENTAL_ENABLE_SQLITE3_LOADABLE_EXT_SUPPORT "enable sqlite3 database loadable extensions support." OFF)
option(FUNDAMENTAL_ENABLE_ROCKSDB_SUPPORT "enable rocksdb database support." OFF)


message(STATUS "FUNDAMENTAL_MAIN_PROJECT=${FUNDAMENTAL_MAIN_PROJECT}")
message(STATUS "FUNDAMENTAL_BUILD_NETWORK=${FUNDAMENTAL_BUILD_NETWORK}")
message(STATUS "FUNDAMENTAL_BUILD_EVENTS=${FUNDAMENTAL_BUILD_EVENTS}")
message(STATUS "FUNDAMENTAL_BUILD_RTTR=${FUNDAMENTAL_BUILD_RTTR}")
message(STATUS "IMPORT_BENCHMARK=${IMPORT_BENCHMARK}")
message(STATUS "IMPORT_GTEST=${IMPORT_GTEST}")
message(STATUS "DISABLE_DEBUG_SANITIZE_ADDRESS_CHECK=${DISABLE_DEBUG_SANITIZE_ADDRESS_CHECK}")


message(STATUS "FUNDAMENTAL_ENABLE_SCRIPT_SUPPORT=${FUNDAMENTAL_ENABLE_SCRIPT_SUPPORT}")
message(STATUS "FUNDAMENTAL_ENABLE_DATABASE_SUPPORT=${FUNDAMENTAL_ENABLE_DATABASE_SUPPORT}")
message(STATUS "FUNDAMENTAL_ENABLE_SQLITE3_SUPPORT=${FUNDAMENTAL_ENABLE_SQLITE3_SUPPORT}")
message(STATUS "FUNDAMENTAL_ENABLE_SQLITE3_LOADABLE_EXT_SUPPORT=${FUNDAMENTAL_ENABLE_SQLITE3_LOADABLE_EXT_SUPPORT}")
message(STATUS "FUNDAMENTAL_ENABLE_ROCKSDB_SUPPORT=${FUNDAMENTAL_ENABLE_ROCKSDB_SUPPORT}")
